application.name=${project.name}
application.version=${project.version}
build.revision=${git.commit.id.full}
build.sourceRef=${git.branch}
build.origin=${eventTiming.buildOrigin}
build.dirty=${git.dirty}
javafx.version=${javafx.version}
